depbuilder stage, remove deploy for now

diff --git a/infra/buildspec.yaml b/infra/buildspec.yaml
--- a/infra/buildspec.yaml
+++ b/infra/buildspec.yaml
@@ -6,51 +6,61 @@ phases:
       - export DOCKER_BUILDKIT=1
       - echo Logging in to Amazon ECR...
       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
-      - echo Pulling the previous image to use as cache...
-      - docker pull $REPOSITORY_URI:builder || echo "No existing image found, proceeding without cache"
+      - |
+        if ! aws ecr describe-images --repository-name $IMAGE_REPO_NAME --image-ids imageTag=latest-rust-1.78.0 --region $AWS_DEFAULT_REGION; then
+          echo "Image not found in ECR, pulling from Docker Hub and pushing to ECR..."
+          docker pull lukemathwalker/cargo-chef:latest-rust-1.78.0
+          docker tag lukemathwalker/cargo-chef:latest-rust-1.78.0 $REPOSITORY_URI:latest-rust-1.78.0
+          docker push $REPOSITORY_URI:latest-rust-1.78.0
+        else
+          echo "Image found in ECR."
+        fi
+      - docker pull $REPOSITORY_URI:depbuilder || echo "No existing image found, proceeding without cache"
       - docker pull $REPOSITORY_URI:latest || echo "No existing image found, proceeding without cache"
 
   build:
     commands:
-      - echo Building the intermediate Docker stages...
-
+      - echo Building dependencies image...
       - |
         docker build \
         --progress=plain \
-        --target builder \
-        --cache-from $REPOSITORY_URI:builder \
+        --target depbuilder \
+        --cache-from $REPOSITORY_URI:depbuilder \
+        --build-arg CARGO_CHEF_IMAGE=$REPOSITORY_URI:latest-rust-1.78.0 \
         --build-arg BUILDKIT_INLINE_CACHE=1 \
-        --tag $API_IMAGE_REPO_NAME:builder \
-        --file Dockerfile .
+        --tag $IMAGE_REPO_NAME:depbuilder \
+        --file aws.Dockerfile .
       - |
-        docker tag $API_IMAGE_REPO_NAME:builder \
-        $REPOSITORY_URI:builder
+        docker tag $IMAGE_REPO_NAME:depbuilder \
+        $REPOSITORY_URI:depbuilder
 
+      - echo Building Docker image...
       - |
         docker build \
-        --progress=plain \
-        --cache-from $REPOSITORY_URI:builder \
+        --cache-from $REPOSITORY_URI:depbuilder \
         --cache-from $REPOSITORY_URI:latest \
+        --build-arg CARGO_CHEF_IMAGE=$REPOSITORY_URI:latest-rust-1.78.0 \
         --build-arg BUILDKIT_INLINE_CACHE=1 \
-        --tag $API_IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION \
-        --file Dockerfile .
+        --progress=plain \
+        --tag $IMAGE_REPO_NAME:latest \
+        --file aws.Dockerfile .
       - |
         docker tag \
-        $API_IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION \
-        $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
-      - |
-        docker tag \
-        $API_IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION \
+        $IMAGE_REPO_NAME:latest \
         $REPOSITORY_URI:latest
 
   post_build:
     commands:
+      - echo Done...
       - echo Pushing the Docker image...
-      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
       - docker push $REPOSITORY_URI:latest
-      - docker push $REPOSITORY_URI:builder
-      - echo Writing image definitions file...
-      - printf '[{"name":"rust-server","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
+      - docker push $REPOSITORY_URI:depbuilder
+#       - echo Writing image definitions file...
+#       - printf '[{"name":"rust-server","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
 
-artifacts:
-  files: imagedefinitions.json
+# artifacts:
+#   files: imagedefinitions.json
+
+cache:
+  paths:
+    - $HOME/.cargo/registry/**/*
